### -=USER=-
GET http://localhost:8189/fitnessab/api/v1/user
Authorization: Basic in_user 123
###
GET http://localhost:8189/fitnessab/api/v1/user/1
Authorization: Basic in_user 123
###
POST http://localhost:8189/fitnessab/api/v1/user
Authorization: Basic in_user 123
Content-Type: application/json

{
  "id": 1,
  "login": "POST_Abramovich",
  "password": "123",
  "matchingPassword": "123",
  "email": "1233@bk.ru",
  "roles": [
    "ROLE_USER",
    "ROLE_ADMIN"
  ]
}
###
PUT http://localhost:8189/fitnessab/api/v1/user
Authorization: Basic in_user 123
Content-Type: application/json

{
  "id": 3,
  "login": "PUT_Abramovich",
  "password": "123",
  "matchingPassword": "123",
  "email": "1233@bk.ru",
  "roles": [
    "ROLE_USER",
    "ROLE_ADMIN"
  ]
}
###
DELETE http://localhost:8189/fitnessab/api/v1/user/2
Authorization: Basic in_user 123
Content-Type: application/json
###
DELETE http://localhost:8189/fitnessab/api/v1/user
Authorization: Basic in_user 123
Content-Type: application/json

### -=ROLE=-
GET http://localhost:8189/fitnessab/api/v1/role
Authorization: Basic in_user 123
###
GET http://localhost:8189/fitnessab/api/v1/role/1
Authorization: Basic in_user 123
###
POST http://localhost:8189/fitnessab/api/v1/role
Authorization: Basic in_user 123
Content-Type: application/json

{
  "id": 123,
  "name": "ROLE_POST"
}
###
PUT http://localhost:8189/fitnessab/api/v1/role
Authorization: Basic in_user 123
Content-Type: application/json

{
  "id": 3,
  "name": "ROLE_POST_PUT"
}
###
DELETE http://localhost:8189/fitnessab/api/v1/role/3
Authorization: Basic in_user 123
Content-Type: application/json
###
DELETE http://localhost:8189/fitnessab/api/v1/role
Authorization: Basic in_user 123
Content-Type: application/json


###  -=MODE=-
GET http://localhost:8189/fitnessab/api/v1/mode
Authorization: Basic in_user 123
###
GET http://localhost:8189/fitnessab/api/v1/mode/1
Authorization: Basic in_user 123
###
POST http://localhost:8189/fitnessab/api/v1/mode
Authorization: Basic in_user 123
Content-Type: application/json

{
  "id": 5,
  "name": "Дополнительное2",
  "isStart": true,
  "descr": ""
}
###
PUT http://localhost:8189/fitnessab/api/v1/mode
Authorization: Basic in_user 123
Content-Type: application/json

{
  "id": 8,
  "name": "PUT_Дополнительное2",
  "isStart": true,
  "descr": ""
}
###
DELETE http://localhost:8189/fitnessab/api/v1/mode/7
Authorization: Basic in_user 123
Content-Type: application/json
###
DELETE http://localhost:8189/fitnessab/api/v1/mode
Authorization: Basic in_user 123
Content-Type: application/json

###  -=CATEGORY=-
GET http://localhost:8189/fitnessab/api/v1/category
Authorization: Basic in_user 123
###
GET http://localhost:8189/fitnessab/api/v1/category/1
Authorization: Basic in_user 123
###
POST http://localhost:8189/fitnessab/api/v1/category
Authorization: Basic in_user 123
Content-Type: application/json

{
  "id": 1,
  "name": "Test",
  "descr": "",
  "creator": {
    "id": 1,
    "login": "abtank",
    "email": "abtank@bk.ru"
  }
}
###
PUT http://localhost:8189/fitnessab/api/v1/category
Authorization: Basic in_user 123
Content-Type: application/json

{
  "id": 10,
  "name": "Test23",
  "descr": "",
  "creator": {
    "id": 1
  }
}
###
DELETE http://localhost:8189/fitnessab/api/v1/category/10
Authorization: Basic in_user 123
Content-Type: application/json
###
DELETE http://localhost:8189/fitnessab/api/v1/category
Authorization: Basic in_user 123
Content-Type: application/json

###  -=EXERSISE=-
GET http://localhost:8189/fitnessab/api/v1/exercise
Authorization: Basic in_user 123
###
GET http://localhost:8189/fitnessab/api/v1/exercise/1
Authorization: Basic in_user 123
###
POST http://localhost:8189/fitnessab/api/v1/exercise
Authorization: Basic in_user 123
Content-Type: application/json

{
  "id": 1,
  "name": "Test",
  "descr": "",
  "creator": {
    "id": 1,
    "login": "abtank",
    "email": "abtank@bk.ru"
  }
}
###
PUT http://localhost:8189/fitnessab/api/v1/exercise
Authorization: Basic in_user 123
Content-Type: application/json

{
  "id": 10,
  "name": "Test23",
  "descr": "",
  "creator": {
    "id": 1
  }
}
###
DELETE http://localhost:8189/fitnessab/api/v1/exercise/10
Authorization: Basic in_user 123
Content-Type: application/json
###
DELETE http://localhost:8189/fitnessab/api/v1/exercise
Authorization: Basic in_user 123
Content-Type: application/json

###  -=WORKOUT=-
GET http://localhost:8189/fitnessab/api/v1/workout
Authorization: Basic in_user 123
###
GET http://localhost:8189/fitnessab/api/v1/workout/1
Authorization: Basic in_user 123
###
POST http://localhost:8189/fitnessab/api/v1/workout
Authorization: Basic in_user 123
Content-Type: application/json

{
  "name": "Test workout 3",
  "descr": "",
  "creator": {
    "id": 1
  }
}
###
PUT http://localhost:8189/fitnessab/api/v1/workout
Authorization: Basic in_user 123
Content-Type: application/json

{
  "id": 5,
  "name": "Test5",
  "descr": "",
  "creator": {
    "id": 1
  }
}
###
DELETE http://localhost:8189/fitnessab/api/v1/workout/5
Authorization: Basic in_user 123
Content-Type: application/json
###
DELETE http://localhost:8189/fitnessab/api/v1/workout
Authorization: Basic in_user 123
Content-Type: application/json

###  -=WORKOUT_EXERSICE=-
GET http://localhost:8189/fitnessab/api/v1/workout_exercise
Authorization: Basic in_user 123
###
GET http://localhost:8189/fitnessab/api/v1/workout_exercise/6
Authorization: Basic in_user 123
###
POST http://localhost:8189/fitnessab/api/v1/workout_exercise
Authorization: Basic in_user 123
Content-Type: application/json

{
  "id": 0,
  "workout": {
    "id": 1
  },
  "exercise": {
    "id": 12
  },
  "mode": {
    "id": 1
  },
  "ordinal": 6,
  "descr": "POST workout_exercise ",
  "creator": {
    "id": 1
  }
}
###
PUT http://localhost:8189/fitnessab/api/v1/workout_exercise
Authorization: Basic in_user 123
Content-Type: application/json

{
  "id": 6,
  "workout": {
    "id": 1
  },
  "exercise": {
    "id": 12
  },
  "mode": {
    "id": 2
  },
  "ordinal": 6,
  "descr": "put workout_exercise",
  "creator": {
    "id": 1
  }
}

###
DELETE http://localhost:8189/fitnessab/api/v1/workout_exercise/6
Authorization: Basic in_user 123
Content-Type: application/json
###
DELETE http://localhost:8189/fitnessab/api/v1/workout_exercise
Authorization: Basic in_user 123
Content-Type: application/json

###  -=ROUND=-
GET http://localhost:8189/fitnessab/api/v1/round
Authorization: Basic in_user 123
###
GET http://localhost:8189/fitnessab/api/v1/round/2
Authorization: Basic in_user 123
###
POST http://localhost:8189/fitnessab/api/v1/round
Authorization: Basic in_user 123
Content-Type: application/json

{
  "id": 0,
  "workout": {
    "id": 1
  },
  "exercise": {
    "id": 1
  },
  "weight": "50",
  "reps": 15,
  "descr": "wow",
  "cardio1": "km",
  "cardio2": "string",
  "cardio3": "string"
}
###
PUT http://localhost:8189/fitnessab/api/v1/round
Authorization: Basic in_user 123
Content-Type: application/json

{
  "id": 3,
  "workout": {
    "id": 1
  },
  "exercise": {
    "id": 1
  },
  "mode": {
    "id": 2
  },
  "ordinal": 6,
  "descr": "put round",
  "creator": {
    "id": 1
  }
}

###
DELETE http://localhost:8189/fitnessab/api/v1/round/3
Authorization: Basic in_user 123
Content-Type: application/json
###
DELETE http://localhost:8189/fitnessab/api/v1/round
Authorization: Basic in_user 123
Content-Type: application/json