server:
  port: 8189
  servlet:
    context-path: /fitnessab

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fitnessAB
    username: postgres
    password: 123
  mvc:
    hiddenmethod:
      filter:
        enabled: true

  #  Hibernate
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        ddl-auto: validate

jwt:
  secret: topsecret12345678901234567890topsecret12345678901234567890topsecret12345678901234567890topsecret12345678901234567890